Basic scala collections performance benchmark from Li Haoyi updated for
scala 2.12

See his https://www.lihaoyi.com/post/BenchmarkingScalaCollections.html[blog post] for 2.11

To run the performance test::
`sbt "bench/runMain bench.Performance <Performance parameters>"`

or

`gradle run --args='<Performance parameters>'`

```
<Performance parameters>:

-e --exec <str>  coma separated list of benchmarks to execute. Benchmarks: build, remove, concat, foreach, index, contains
-s --skip <str>  coma separated list of benchmarks not to execute. Benchmarks: build, remove, concat, foreach, index, contains
-t --time <int>  How long each benchmark runs, in millisecs
-l --loop <int>  How many times to repeat each benchmark
-o --out <str>   Name of the result file
```

To run the memory test::
`sbt "bench/runMain bench.Memory"`

or

`gradle run -Pbench=Memory`

Note:: gradle run does not find the agent TODO: Fix `applicationDefaultJvmArgs`

=== Changes
- do not initialize test case @ each execution
- do not run initialization for 2sec before test case execution
- removed ammonite dependency

=== Added features
- repetition can be passed as main program argument to `Performance` benchmark (defaulted to 7)
- array and buffer indexing extracted from "lookup" benchmark into: "index"
- grade build added
- `Analyze` can take the result file name as command line parameter
- benchmark case 'Set' 'concat' uses unique values